version: '3.8'

services:
  app:
    container_name: mongo_songs
    restart: always
    build: .
    ports:
      - '3000:3000'
    links: 
    - mongo
  
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    ports:
      - "27017:27017"
